CC = gcc
CFLAGS = -Wall -Wextra

all:
	$(CC) $(CFLAGS) hello.c -o hello
	$(CC) $(CFLAGS) presentation.c -o presentation
	$(CC) $(CFLAGS) variables.c -o variables
	$(CC) $(CFLAGS) code_sortie.c -o code_sortie
	$(CC) $(CFLAGS) programme1_corrige.c -o programme1_corrige
	$(CC) $(CFLAGS) programme2_corrige.c -o programme2_corrige
	$(CC) $(CFLAGS) programme3_corrige.c -o programme3_corrige
	$(CC) $(CFLAGS) programme4_corrige.c -o programme4_corrige
	$(CC) $(CFLAGS) fiche.c -o fiche

clean:
	rm -f hello presentation variables code_sortie
	rm -f programme1_corrige programme2_corrige
	rm -f programme3_corrige programme4_corrige fiche
