CC = gcc
CFLAGS = -Wall -Wextra -std=c11

all:
	$(CC) $(CFLAGS) notes.c -o notes
	$(CC) $(CFLAGS) table.c -o table
	$(CC) $(CFLAGS) fonctions.c -o fonctions
	$(CC) $(CFLAGS) statistiques.c -o statistiques
	$(CC) $(CFLAGS) pointeurs.c -o pointeurs
	$(CC) $(CFLAGS) devine.c -o devine

clean:
	rm -f notes table fonctions statistiques pointeurs devine
